config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'pages#home'

  resources :jobs, only: %i[new create index show destroy] do
    resources :proposals, only: %i[new create update edit show destroy]
    resources :review, only: %i[new create]
  end
 
  # creating user/:id
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :proposals, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_language,
                  against: [:content],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :job
  belongs_to :user

  validates :deadline, presence: true
  validates :price, presence: true
  validates_numericality_of :price, greater_than_or_equal_to: 0

  validate :deadline_after_today

  private

  def deadline_after_today
    return if deadline.blank?

    errors.add(:deadline, " - A data de entrega deverá ser uma data futura!") if deadline <= Date.today
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :proposals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  include Pundit
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

    def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :photo, :skill])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :photo, :skill])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show destroy]

  def index
    # @restaurants = Restaurant.all
    if params[:query].present?
      @jobs = policy_scope(Job.search_by_language(params[:query]))
    else
      @jobs = policy_scope(Job.all).order(created_at: :desc)
    end
  end

  def show
    @proposals = Proposal.where(job_id: @job.id).order(status: :asc)

    @accepted_proposal = Proposal.where(job_id: @job.id, status: "accepted")[0]

  end

  def new
    @job = Job.new
    authorize @job
  end

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    authorize @job

    if @job.save
      redirect_to @job, notice: 'Sua demanda de tradução foi criada com sucesso.'
    else
      render :new
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_url, notice: 'A demanda de tradução foi apagada com sucesso.'
  end

  # ==>> CONTINUAR <<===
  # def my_jobs
  #   @jobs = policy_scope(Job).find(@proposal.job_id).where(@proposal.user_id == current_user)
  #   # .order(created_at: :desc)
  # end

  private

  def job_params
    params.require(:job).permit(:content)
  end

  def set_job
    @job = Job.find(params[:id])
    authorize @job
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: %i[edit update]
  before_action :set_job, only: %i[new create edit update]

  def new
    @proposal = Proposal.new
  end

  def create
    @job = Job.find(params[:job_id])
    @proposal = Proposal.new(proposal_creation_status_params)
    @proposal.job_id = @job.id
    @proposal.user_id = current_user.id
    @proposal.status = "pending"

    if @proposal.save
      redirect_to @job, notice: "The proposal was successfully created."
    else
      render :new
    end
  end

  def edit
    days_to_due_date = (Date.today - @proposal.deadline).ceil.abs
    @date = "#{@proposal.deadline.strftime('%d.%m.%Y')} (#{days_to_due_date} #{ days_to_due_date > 1 ? "dias" : "dia"})"
  end

  def update
    @proposal.update(proposal_status_params)
    redirect_to @job, notice: "The proposal was successfully updated."
  end

  def destroy
    @proposal = Proposal.find(params[:id])
    if current_user.admin || @proposal.user_id == current_user.id
      @proposal.delete
      redirect_to user_path(current_user), notice: "The proposal was successfully deleted."
    end
  end

  private

  def set_job
    @job = Job.find(params[:job_id])
  end

  def proposal_creation_status_params
    params.require(:proposal).permit(:price, :deadline)
  end

  def proposal_status_params
    params.require(:proposal).permit(:status)
  end

  def set_proposal
    @proposal = Proposal.find(params[:id])
    authorize @proposal
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @jobs = Job.where(user_id: @user.id)
    @proposals = Proposal.where(user_id: @user.id)
    
    if params[:filter].present?
      query = "proposals.user_id = ? AND proposals.status = ?"
      @proposals = Proposal.joins(:job).where(query, @user.id, params[:filter])
    end
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/index.html.erb
<div class="container mt-3 center-block">
  <div class="search mt-3 col-5 mx-auto justify-content-between">
    <%= form_tag jobs_path, method: :get, class: "form-inline" do %>
    <div class="col-md-9 col-sm-12">
      <%= text_field_tag :query,
      params[:query],
      class: "form-control search-bar",
      placeholder: "Encontre um idioma"
      %>
    </div>
    <div class="col-md-2 col-sm-6">
      <%= submit_tag "Procurar", class: "btn btn-green ml-2" %>
    </div>
    <% end %>
  </div>
  <hr>
  <div class="jobs-all mt-3 col-md-12 col-sm-9 d-flex flex-wrap justify-content-around">
    <% @jobs.each do |job| %>
    <div class="card mt-4 col-md-5 col-sm-12">
      <div class="card-body d-flex flex-wrap">
        <div class="col-9 card-text">
          <% if job.user.photo.attached? %>
          <%= cl_image_tag job.user.photo.key, quality: "auto", fetch_format: :auto, crop: :fill, style: 'height:48px; width: auto;', class: "border avatar avatar-large avatar-job avatar-bordered" %>
          <% else %>
          <%= image_tag "person-placeholder.jpg", quality: "auto", fetch_format: :auto, crop: :fill, style: 'height:48px; width: auto;', class: "border avatar avatar-job" %>
          <% end %>
          <h5 class="mt-4"><%= link_to "Tradução: #{job.content}", job_path(job) %></h5>
          <p> <%= link_to "@#{job.user.username}", user_path(job.user) %> </p>
        </div>
        <div class="col-3 card-text d-flex flex-column align-items-end">
          <% if current_user.id != job.user_id %>
          <%= link_to 'Fazer proposta', new_job_proposal_path(job), class: 'btn btn-green btn-small' %>
          <% end %>
          <br>
          <% accepted_proposal = job.proposals.select { |proposal| proposal.status == "accepted" } %>
          <br>
          <% if policy(job).destroy? && accepted_proposal.size != 1 %>
          <p><%= link_to 'Apagar', job, method: :delete, data: { confirm: 'Tem certeza que deseja apagar essa demanda de tradução?' }, class: 'btn btn-green btn-delete btn-small' %></p>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div style="min-height: 5vh;">
</div>

app/views/jobs/my_jobs.html.erb
<h1>Jobs for fulaninho</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Content</th>      
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.id %></td>
        <td><%= job.content %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<div class = "container mt-5">
  <h1>Nova solicitação de tradução</h1>
  <%= simple_form_for (@job) do |f| %>        
    <%= f.input :content, label: "Descreva sua demanda. \n
    Seja o mais preciso possível: número de páginas, tipo de documento, idiomas de origem e destino" %>       
   <div class="row">
   <%= f.submit "Criar pedido", class: 'btn btn-green my-3 mx-3', label: "Criar pedido" %>      
   <%= link_to 'Voltar', jobs_path, class: 'btn btn-green my-3 mx-3' %>
    </div>
  <% end %>

 
</div>

        <div style="min-height: 61vh;">
        </div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="show-content d-flex">
    <div class="job-info col-6">
      <div class="card-livro">
        <img src="https://picsum.photos/id/24/200/300" />
        <div class="card-trip-infos">
            <h4 class="mt-2">Serviço de tradução</h4>
            <h2 class="ml-1 mr-1"><%= @job.content %></h2>
        </div>
      </div>
    </div>
    <div class="proposals-info col-6">
      <div class="card card-proposal-show card-livro">
        <div class="d-flex justify-content-between mr-1 mt-1 align-items-center">
          <h3 class="pl-2 mt-2 pb-2">Propostas recebidas</h3>
          <% if current_user.id != @job.user_id %>
            <%= link_to 'Fazer proposta', new_job_proposal_path(@job), class: "btn btn-green btn-small"%>
          <% end %>
        </div>

        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Usuário</th>
              <th scope="col">Preço</th>
              <th scope="col">Prazo</th>
              <th scope="col">Status</th>
            </tr>
          </thead>

           <% @proposals.each_with_index do |proposal| %>
            <% if proposal.status == 'accepted' %>
              <tr class='table-success'>
            <% elsif proposal.status == 'rejected'%>
              <tr class='table-danger'>
            <% else %>
              <tr>
            <% end %>
           <% end %>

          <% @proposals.each_with_index do |proposal| %>
              <th scope="row" class=<%= "#{proposal.status}-status"%>><i class="fas fa-circle"></i></th>
              <td><%= User.find(proposal.user_id).username %></td>
              <td><%=  number_to_currency(proposal.price, precision: 2, unit: "R$", separator: ",") %></td>
              <td><%= proposal.deadline.strftime("%d.%m.%Y") %></td>
              <td>
                <% proposal.status = "pending" if proposal.status.nil? %>
                <% if proposal.status == "accepted" %>
                  <% proposta = "Aceito" %>
                <% elsif proposal.status == "rejected" %>
                  <% proposta = "Rejeitado" %>
                <% else %>
                  <% proposta = "Pendente"  %>
                <% end %>

                <% if proposal.job.user.username == current_user.username || current_user.admin %>
                  <%= link_to proposal.status.capitalize, edit_job_proposal_path(@job, proposal) %>
                <% else %>
                  <%= proposta %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="modal fade <%= 'accepted' if  @accepted_proposal %>" id="completedModal" tabindex="-1" role="dialog" aria-labelledby="completedModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="completedModalLabel">Que bom que você achou o que queria! 😃</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% if @accepted_proposal %>
      <div class="modal-body">
        Agora você precisa entrar em contato com @<%= User.find(@accepted_proposal.user_id).username if @accepted_proposal %> para os ajustes finais:
        <br>
        Nome: <%= "#{User.find(@accepted_proposal.user_id).first_name} #{User.find(@accepted_proposal.user_id).last_name}" %>
        <br>
        E-mail: <%= User.find(@accepted_proposal.user_id).email %>
      </div>
      <% end %>
      <div class="modal-footer">
        <button type="button" class="btn btn-green" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>
<div style="min-height: 42vh;">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TraduzFacil</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div id="notice">
    </div>
    <% unless current_page?(root_path) || current_page?(new_user_session_path) %>
    <%= render partial: "share/navbar" %>
    <% end %>
    <%= render partial: "share/flashes" %>
    <%= yield %>
    <% unless current_page?(root_path) || current_page?(new_user_session_path) %>
    <%= render partial: "share/footer" %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner d-flex flex-column">
  <div class="navbar navbar-expand-sm navbar-light navbar-landing">
    <div></div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li>
          <form class="form-inline my-2 my-lg-0" hidden>
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-green my-2 my-sm-0" type="submit">Search</button>
          </form>
        </li>
        <li class="nav-item dropdown ml-2">
          <% if current_user && current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% elsif current_user %>
            <%= image_tag "person-placeholder.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: "btn btn-green" %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user %>
              <%= link_to "Minha página", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Demandar uma tradução", new_job_path, class: "dropdown-item" %>
              <%= link_to "Procurar por serviços", jobs_path, class: "dropdown-item" %>
              <%= link_to "Editar meu Perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Entrar na conta", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Criar uma conta", new_user_registration_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div class="col-8 px-5 pt-5 container" >
    <div class="title-banner mt-2">
      <h1><%= image_tag "logo-traduz-simples.png" %> traduz fácil</h1>
      <h5><em>Ache alguém que vai te entender</em></h5>
      <p><strong>A melhor plataforma de conexão entre tradutores e clientes</strong></p>
    </div>
  </div>
  <div class="banner-options d-flex justify-content-around">
    <div class="row">
      <div class="col-sm-9 col-md-6">
        <div class="card card-home">
          <div class="card-body">
            <div class="button-action d-flex justify-content-around">
              <%= link_to "Faça agora seu pedido ", new_job_path, :class => 'btn-green' %>
            </div>
            <br>
            <div class="info-action">
              <h5 class="card-title"><strong>Para quem precisa de traduções</strong></h5>
              <p class="card-text">Cadastre aqui seu pedido e receba cotações.
                Verifique preço e prazo antes de decidir.</p>
            </div>
          </div>
          </div>
        </div>
        <div class="col-sm-9 col-md-6">
          <div class="card card-home">
            <div class="card-body card-tradutores">
              <div class="button-action d-flex justify-content-around">
                <%= link_to "Encontre sua próxima tradução", jobs_path, :class => 'btn-green' %>
              </div>
              <br>
              <div class="info-action">
                <h5 class="card-title"><strong>Para tradutores</strong></h5>
                <p class="card-text">Encontre clientes e oportunidades de trabalho. Mostre a qualidade de seu trabalho!</p>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/proposals/edit.html.erb
<div class="container">
  <h2 class="edit-title mt-4">Verificar proposta</h2>
  <div class="col-6 mt-4 mb-4">
    <table class="table table-striped">
      <tbody>
        <tr>
          <th scope="row">Descrição do serviço:</th>
          <td><%= Job.find(@proposal.job_id).content %></td>
        </tr>
        <tr>
          <th scope="row">Usuário:</th>
          <td><%= User.find(@proposal.user_id).username %></td>
        </tr>
        <tr>
          <th scope="row">Preço proposto:</th>
          <td>R$ <%= @proposal.price %></td>
        </tr>
        <tr>
          <th scope="row">Prazo proposto:</th>
          <td><%= @date %></td>
        </tr>
      </tbody>
    </table>
  </div>

    <%= simple_form_for [ @job, @proposal ], :html => {:class => 'form-group ml-4'} do |f| %>
    <div class="row">
      <%= f.label :status, class:"edit-label col-1 br-0 pr-0" %>
      <div class="edit-options col-4 bl-0 pl-0">
        <%= f.collection_radio_buttons :status, [
        ['pending', 'Pendente'],
        ['accepted', 'Aceito'],
        ['rejected', 'Rejeitado']],
        :first, :last, item_wrapper_tag: :div %>
      </div>
    </div>
    <br>
    <%= f.submit "Aceitar Proposta" class:"btn btn-green" %>
    <% end %>
  <hr>
  <div class="mb-3">
  <%= link_to :back do %>
    <i class="fas fa-history"> Voltar </i>
  <% end %>
  </div>
</div>

app/views/share/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h5><%= image_tag "logo-traduz-simples.png" %> <span class="title">traduz fácil</span></h5>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <form class="form-inline my-2 my-lg-0" hidden>
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-green my-2 my-sm-0" type="submit">Search</button>
        </form>
      </li>
      <li class="nav-item dropdown ml-2">
        <% if current_user && current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "person-placeholder.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user %>
            <%= link_to "Minha página", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Demandar uma tradução", new_job_path, class: "dropdown-item" %>
            <%= link_to "Procurar por serviços", jobs_path, class: "dropdown-item" %>
            <%= link_to "Editar meu Perfil", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Entrar na conta", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "Criar uma conta", new_user_registration_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/share/_table_jobs.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Descrição</th>
      <th scope="col">Número de propostas</th>
    </tr>
  </thead>
  <tbody>
    <% jobs.each do |job| %>
      <tr>
      <th scope="row" class=<%= job.completed ? "accepted-status" : "pending-status" %>><i class="fas fa-circle"></i></th>
      <td><%= link_to job.content, job_path(job) %></td>
      <td><%= job.proposals.count  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/share/_table_proposal.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Usuário</th>
      <th scope="col">Preço</th>
      <th scope="col">Prazo</th>
      <th scope="col">Status</th>
      <th scope="col">Apagar</th>
    </tr>
  </thead>
  <tbody id="proposalT">
    <% proposals.each do |proposal| %>
      <% if proposal.status == 'accepted' %>
        <tr class='table-success'>
      <% elsif proposal.status == 'rejected'%>
        <tr class='table-danger'>
      <% else %>
        <tr>
      <% end %>
      <th scope="row" class=<%= "#{proposal.status}-status"%>><i class="fas fa-circle"></i></th>
      <td><%= link_to Job.find(proposal.job_id).user.username, job_path(proposal.job_id) %></td>
      <td>R$<%= proposal.price %></td>
      <td><%= proposal.deadline.strftime("%d.%m.%Y") %></td>

      <% if proposal.status == "accepted" %>
        <td><a href="/" type="button" data-toggle="modal" data-target="#acceptedProposal" id ="proposalBox" data-proposalid="<%= proposal.id %>">
          <%= proposal.status.capitalize %>
        </a></td>  
      <% else %>
        <td><%= proposal.status.capitalize %></td>
      <% end %>
      <% if current_user.admin || proposal.user_id == current_user.id  %>
        <td>
          <%= link_to job_proposal_path(proposal.job_id, proposal), method: "Delete", class: "green-font", data: {confirm: "Tem certeza?"} do %>
              <i class="fas fa-trash-alt"></i>
          <% end %>
        </td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="container d-flex">
  <div class="user_info">
    <div class="card mt-3 mb-3">
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, height: 225, width: 300, crop: :fill %>
      <% else %>
        <%= image_tag "person-placeholder.jpg", height: 225, width: 300, crop: :fill %>
      <% end %>
      <div class="card-body d-flex justify-content-between">
        <div class="info flex-grow">
          <h5 class="card-title">@<%= @user.username %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= " #{@user.first_name} #{@user.last_name}" %></h6>
          <p class="card-text">Idioma: <%= @user.skill %></p>
        </div>
        <% if current_user == @user %>
        <div class="edit-profile">
          <%= link_to edit_user_registration_path @user do %>
            <i class="fas fa-user-edit"></i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="jobs-proposal-info ml-5 mt-3 mb-3 card card-jb-info col-8">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab"  data-toggle="tab" href="#jobs" role="tab" aria-controls="home" aria-selected="true">Traduções Requisitadas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#proposals" role="tab" aria-controls="profile" aria-selected="false" >Minhas propostas</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show  active box_fora" id="jobs" role="tabpanel" aria-labelledby="jobs-tab">
        <div>
          <div class="card card-proposal-show card-livro pb-10 box_dentro">
            <h3 class="mt-2 pb-2 pl-3 pt-2">Trabalhos solicitados</h3>
            <%= render partial: "share/table_jobs", locals: { jobs: @jobs } %>
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="proposals" role="tabpanel" aria-labelledby="proposals-tab">
        <div class="card card-proposal-show card-livro">
          <h3 class="mt-2 pb-2 pl-3 pt-2"> Propostas enviadas </h3>
          <div class="dropdown">
            <button class="btn btn-secondary active btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Status
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to 'Pendente', users_show_path(filter: 'pending', id: current_user.id), class: 'dropdown-item' %>
              <%= link_to 'Aceito', users_show_path(filter: 'accepted', id: current_user.id), class: 'dropdown-item' %>
              <%= link_to 'Rejeitado', users_show_path(filter: 'rejected', id: current_user.id), class: 'dropdown-item' %>
              <%= link_to 'Todos', users_show_path(id: current_user.id), class: 'dropdown-item' %>
            </div>
          </div>
          <p></p>
          <%= render partial: "share/table_proposal", locals: { proposals: @proposals, job: @job } %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="acceptedProposal" tabindex="-1" role="dialog" aria-labelledby="acceptedProposalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="acceptedProposalLabel">Que bom que a sua proposta foi aceita! 😃</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          O usuário entrará em contato com você!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-green" data-dismiss="modal">Ok</button>
        </div>
      </div>
    </div>
  </div>
</div>
        <div style="min-height: 55vh;">        </div>
<!-- Modal -->